# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaApprovals',
            fields=[
                ('approve_id', models.IntegerField(primary_key=True, serialize=False)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pa_approvals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaDocuments',
            fields=[
                ('document_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, max_length=45, null=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=45, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('score_date', models.DateTimeField(blank=True, null=True)),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pa_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaItems',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=45)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('display_rank', models.IntegerField(blank=True, null=True)),
                ('item_number', models.CharField(blank=True, max_length=45, null=True)),
                ('score_points', models.CharField(blank=True, max_length=45, null=True)),
                ('section_number', models.CharField(blank=True, max_length=45, null=True)),
                ('description_th', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('hint_th', models.CharField(blank=True, max_length=500, null=True)),
                ('hint_en', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'pa_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaLines',
            fields=[
                ('line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_number', models.CharField(blank=True, max_length=45, null=True)),
                ('description_th', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_details', models.CharField(blank=True, max_length=500, null=True)),
                ('score_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('score_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('score_deadline', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pa_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'staffs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Staffs')),
                ('program_id', models.CharField(blank=True, max_length=45, null=True)),
                ('rank', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'academic_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Staffs')),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'executive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Staffs')),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'support_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.AcademicStaff')),
            ],
            options={
                'db_table': 'academic_program',
                'managed': False,
            },
        ),
    ]
